name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Setup Java
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: 'agents'
          path: './build/*.jar'