name: Create Release

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    uses: './.github/workflows/build.yml'

  release:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3.0.0
        with:
          name: 'agents'
          path: './agents'

      - name: Get Release Name
        id: name
        run: echo "::set-output name=title::${GITHUB_REF##*/v}"

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          name: ${{ steps.name.outputs.title }}
          draft: false
          fail_on_unmatched_files: true
          files: './agents/*'